ktor:
  application:
    modules:
      - com.auth.ApplicationKt.module
  deployment:
    port: 8080


jwt:
  secret: yunnote
  issuer: ktor-auth
  audience: ktor-auth-service
  realm: Access ALL
  access-token-expire: 60  # 1시간
  refresh-token-expire: 43200 # 30일
